### ISSUE TITLE
Add 3 new input vars for make vulnerability-free buckets

### ISSUE THREAD

**Issue by bcarranza** [cloudposse/terraform-aws-vpc-flow-logs-s3-bucket#46]
## Describe the Feature

Give the user the opportunity to use three important variables to mitigate vulnerabilities in s3 buckets.

- versioning_enabled
- acl
- s3_object_ownership

## Expected Behavior

In the assignment of these variables you leave it up to the user to decide whether to use acls or not, whether the buckets can only be used by the account that owns the bucket, and whether to activate or deactivate the versioning on the bucket.

## Use Case

In PCI-DSS certification it is necessary to run prowlers that evaluate the entire aws infrastructure in a given region.
The [terraform-aws-vpc-flow-logs-s3-bucket](https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket) project is a great alternative to overcome the vpc flow log vulnerability, however the s3 bucket that this project needs is being created with vulnerabilities, so you solve the vpc log problem but generate new issues.

## Describe Ideal Solution

Expose the vars as input vars of this module: https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/blob/master/variables.tf

## Additional Context

The following is a group of vulnerabilities that are violated by not being able to use the aforementioned variables

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.4">
</head>
<body>

Result | Severity | AccountID | Region | Compliance | Service | CheckID | Check Title | Check Output | CIS Level | CAF Epic | Risk | Remediation | Docs | Resource ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
FAIL | Medium | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.172 | [extra7172] Check if S3 buckets have ACLs enabled | us-west-2: Bucket xxxx-x2-ops-vpc-aws-flow-log has bucket ACLs enabled! | Extra | Logging and Monitoring | S3 ACLs are a legacy access control mechanism that predates IAM. IAM and bucket policies are currently the preferred methods. | Ensure that S3 ACLs are disabled (BucketOwnerEnforced). Use IAM policies and bucket policies to manage access. |   | xxxxx-x2-ops-vpc-aws-flow-log
FAIL | Medium | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.18 | [extra718] Check if S3 buckets have server access logging enabled | us-west-2: Bucket xxxxx-x2-ops-vpc-aws-flow-log has server access logging disabled! | Extra | Logging and Monitoring | Server access logs can assist you in security and access audits; help you learn about your customer base; and understand your Amazon S3 bill. | Ensure that S3 buckets have Logging enabled. CloudTrail data events can be used in place of S3 bucket logging. If that is the case; this finding can be considered a false positive. |   | xxxxx-x2-ops-vpc-aws-flow-log
FAIL | Medium | xxxxx | us-west-2 | Software and Configuration Checks | s3 | 7.63 | [extra763] Check if S3 buckets have object versioning enabled | us-west-2: Bucket xxxxxx-x2-ops-vpc-aws-flow-log has versioning disabled! | Extra | Data Protection | With versioning; you can easily recover from both unintended user actions and application failures. | Configure versioning using the Amazon console or API for buckets with sensitive information that is changing frecuently; and backup may not be enough to capture all the changes. |   | xxxxxxx-x2-ops-vpc-aws-flow-log

</body>
</html>

**Comment by Nuru** [comment]
closed by #47
