### ISSUE TITLE
Error: "name" must begin with 'alias/' and be comprised of only [a-zA-Z0-9/_-]

### ISSUE THREAD

**Issue by roeera** [cloudposse/terraform-aws-vpc-flow-logs-s3-bucket#48]
## Describe the Bug
Error while using the module while running tf plan

## Screenshots

![image](https://user-images.githubusercontent.com/9716609/178475091-e3546411-ef12-4ce8-bfe3-e586b9c68fc1.png)

## Environment (please complete the following information):

module version: latest
tf version: 1.2.2

**Comment by Nuru** [comment]
You must provide some kind of name for the bucket via one or more of the [null-label](https://github.com/cloudposse/terraform-null-label/) inputs.
