### ISSUE TITLE
New S3 default policy breaks creation of S3 bucket

### ISSUE THREAD

**Issue by victor-chan-groundswell** [cloudposse/terraform-aws-vpc-flow-logs-s3-bucket#53]
It would seem that Amazon is pushing S3 bucket defaults that's breaking the module.

https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-s3-two-security-best-practices-buckets-default/

Unfortunately, this means that, with the combination of default settings, the s3 bucket doesn't create as it appears that the default policy that it sets in is incompatible with the bucket policy that is trying to put in.

![image](https://user-images.githubusercontent.com/91491301/233122532-49dfed86-97e2-45e3-bb6f-b407c14dce64.png)

I'm going to try to workaround this buy actually getting the module and tweaking the settings of the downstream s3 module to allow ACLs to see if it works.

**Comment by victor-chan-groundswell** [comment]
Form what I have experimented so far...., changing a setting so that I can set s3_object_ownership to "BucketOwnerPreferred" has a okay workaround....

![image](https://user-images.githubusercontent.com/91491301/233136875-6c4b12d2-f216-42e8-a29e-9f3a21e7159d.png)

in that, in the 1st TF run, I still run into this, but if I ran TF apply again a 2nd time, then everything gets applied and set.

![image](https://user-images.githubusercontent.com/91491301/233136659-6e04b3a7-a42d-46b0-95f0-780a86082613.png)

I think it might have something to deal with how the cloudposse/s3-log-storage/aws module sets up the ACL....

https://github.com/hashicorp/terraform-provider-aws/issues/28353

**Comment by awarner-greshamtech** [comment]
Isn't the default for the s3_object_ownership input variable already BucketOwnerPreferred?

**Comment by Nuru** [comment]
This has been fixed in the upstream [terraform-aws-s3-bucket](https://github.com/cloudposse/terraform-aws-s3-bucket) and will be fixed in the next release of this module.
