### ISSUE TITLE
terraform-aws-s3-log-storage.git?ref=tags/0.7.0 is outdated

### ISSUE THREAD

**Issue by ismailyenigul** [cloudposse/terraform-aws-vpc-flow-logs-s3-bucket#8]
module Git URL at 
https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/blob/master/main.tf#L95
should be updated with the latest tag which is 0.12.0 https://github.com/cloudposse/terraform-aws-s3-log-storage/tree/0.12.0

**Comment by Gowiem** [comment]
This was recently updated by release [`0.6.0`](https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/releases/tag/0.6.0). Closing out!
